// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/register-device": {
            "post": {
                "description": "Register a new device and receive a device token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Register device",
                "parameters": [
                    {
                        "description": "device info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/repos/{repo}/changes": {
            "get": {
                "description": "List changes since an ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "changes"
                ],
                "summary": "List changes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repo",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "since id",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Push local changes to the server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "changes"
                ],
                "summary": "Push changes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "repo",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "changes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PostChangesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.PostChangesRequest": {
            "type": "object",
            "required": [
                "changes",
                "device_token"
            ],
            "properties": {
                "changes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Change"
                    }
                },
                "device_token": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterDeviceRequest": {
            "type": "object",
            "required": [
                "device_id",
                "repo"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                }
            }
        },
        "models.Change": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "Attachments stored as JSON string for MVP",
                    "type": "string"
                },
                "base_sha": {
                    "type": "string"
                },
                "change_id": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "file_uid": {
                    "type": "string"
                },
                "new_sha": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
